### ISSUE TITLE
any easy way to expose keyed_hash() and derive_key()?

### ISSUE THREAD

**Issue by oconnor663** [xoofx/Blake3.NET#1]
I heard from a programmer who went looking for .NET bindings that exposed those features, and they weren't able to find anything. I'm not up to speed on .NET myself, but if there's any way I can help with this (including making upstream changes) please let me know.

**Comment by xoofx** [comment]
There is this file [lib.rs](https://github.com/xoofx/Blake3.NET/blob/master/lib/blake3_dotnet/src/lib.rs) to modify to expose the Rust API. Then it will have to be exposed in C#.
I will have then to republish the native binaries with it. PR welcome.

**Comment by xoofx** [comment]
Oh sorry, you are the actual maintainer of Blake3! 😅 
So I will take it from there, I don't know when but you can redirect the C# user asking for this here and he might be willing to do a PR!

**Comment by samuel-lucas6** [comment]
Hi! I've had a look at the code and don't think I have the skill to do a PR. For example, I have no understanding of Rust. So I'm afraid it's probably best left to you.

**Comment by oconnor663** [comment]
And I haven't written C# in about 10 years 😁 But I bet the only Rust coding required would be duplicating [this exported Rust function](https://github.com/xoofx/Blake3.NET/blob/master/lib/blake3_dotnet/src/lib.rs#L3-L7) (which currently calls the [`blake3::Hasher::new`](https://docs.rs/blake3/0.3.7/blake3/struct.Hasher.html#method.new) function in my API) to add similar wrappers for [`blake3::Hasher::new_keyed`](https://docs.rs/blake3/0.3.7/blake3/struct.Hasher.html#method.new_keyed) and [`blake3::Hasher::new_derive_key`](https://docs.rs/blake3/0.3.7/blake3/struct.Hasher.html#method.new_derive_key). The bulk of the change would be figuring out exactly how to expose those through the C# API.

**Comment by samuel-lucas6** [comment]
> 
> 
> And I haven't written C# in about 10 years 😁 But I bet the only Rust coding required would be duplicating [this exported Rust function](https://github.com/xoofx/Blake3.NET/blob/master/lib/blake3_dotnet/src/lib.rs#L3-L7) (which currently calls the [`blake3::Hasher::new`](https://docs.rs/blake3/0.3.7/blake3/struct.Hasher.html#method.new) function in my API) to add similar wrappers for [`blake3::Hasher::new_keyed`](https://docs.rs/blake3/0.3.7/blake3/struct.Hasher.html#method.new_keyed) and [`blake3::Hasher::new_derive_key`](https://docs.rs/blake3/0.3.7/blake3/struct.Hasher.html#method.new_derive_key). The bulk of the change would be figuring out exactly how to expose those through the C# API.

Good point, but I'm still not convinced I'd implement things correctly. I've never really worked with pointers or Spans before. I don't know which C# files need to modified as I don't have a good enough understanding of the API. This would also be my first proper PR.

It would be a good learning exercise, but it's probably best left to the pros. I think contributing to existing code is in many ways harder than writing your own from scratch, and @xoofx has a lot more programming experience than me.

**Comment by xoofx** [comment]
This is fixed in 0.3.0
