### ISSUE TITLE
suggested improvement

### ISSUE THREAD

**Issue by rfrfrf** [xoofx/Blake3.NET#11]
Shouldn't the code in lines
https://github.com/xoofx/Blake3.NET/blob/master/src/Blake3/Blake3Stream.cs#L86
and
https://github.com/xoofx/Blake3.NET/blob/master/src/Blake3/Blake3Stream.cs#L97
be changed to
`new Span<byte>(buffer, offset, length)`
i.e., use the actual `length`?

And if so, according changes to lines 109 and 119 seem logical.

**Comment by xoofx** [comment]
Yes.  indeed, it's a bug, PR welcome

**Comment by xoofx** [comment]
There are many other suspicious places I think like https://github.com/xoofx/Blake3.NET/blob/master/src/Blake3/Blake3Stream.cs#L119 not sure what I drunk when I wrote this code 😅

**Comment by rfrfrf** [comment]
PR submitted, see https://github.com/xoofx/Blake3.NET/pull/12
