### ISSUE TITLE
Is Hasher reentrant?

### ISSUE THREAD

**Issue by dnovatchev** [xoofx/Blake3.NET#13]
This is just a question:

> Are the methods of the Hasher class reentrant, thus can we use a singleton  (`AddSingleton()`) Hasher to pass it with dependency injection for the needs of processing many concurrent web requests?
> 
> Or, should we create a new instance (`AddScoped()`) for each request?

**Comment by xoofx** [comment]
Static methods are reentrant. Instance methods on `Hasher` are not because `Hasher` contains the current state of what is being hashed, so definitely not a multi-threaded shareable instance. Unless you guarantee that the singleton is always used concurrently.

**Comment by dnovatchev** [comment]
Thank you, Alexandre!

Maybe putting this one sentence in the readme.md file would be useful to people like me 😄
