### ISSUE TITLE
Can't compile blake3 in VS2019

### ISSUE THREAD

**Issue by HananSalemsys** [xoofx/Blake3.NET#14]
hi 
i am a student and my research is on blake3 hash function 
i download your source code of blake3 in c# from github 
and use  visual studio 2019 to run the code and install [NET 5 SDK] as you say 
But unfortunately the code not executed and the following error appear 

"the debug profile "Blake3"is missing the path to the executable to debug"
Note that I did change the properties of project to executable 

![image](https://user-images.githubusercontent.com/77951057/157882180-d44f4f35-91be-4f62-bddb-4e3ac9bb2a55.png)

could you help me and guide me what can i do else to run the code , please ?
Best Regards

**Comment by xoofx** [comment]
I forgot to update the documentation, as I switched the project to .NET 6.0 by commit 03f9487a11dbbeea89970c1b8d025c6ad32c4078 so that's why VS2019 cannot load this project anymore.

So you will need to download latest VS2022 in order to build Blake3.NET

I'm gonna update the front readme.

**Comment by silkfire** [comment]
Blake3 is a _library_, it's rather obvious that there's nothing to execute. You need to create a separate _executable_ project type (e.g. console application or an ASP.NET Core project) that references Blake3 and then execute that.

**Comment by xoofx** [comment]
> But unfortunately the code not executed and the following error appear
> Blake3 is a _library_, it's rather obvious that there's nothing to execute.

Oh, you are right, I missed that important part actually 😅

**Comment by HananSalemsys** [comment]
i use VS2022 and build the project the following error appear
[image: error.jpg]
Please tell me why this error occurred and how I can fix it
And how can I use the code correctly. Thank you for your response

‫في السبت، 12 مارس 2022 في 7:37 ص تمت كتابة ما يلي بواسطة ‪Alexandre
Mutel‬‏ ***@***.***‬‏>:‬

**Comment by HananSalemsys** [comment]
i use VS2022 and build the project the following error appear 
![error](https://user-images.githubusercontent.com/77951057/158012874-82a27a22-1171-461e-8fe3-333d43ec7850.jpg)

Please tell me why this error occurred and how I can fix it
And how can I use the code correctly. Thank you for your response
what this error mean ??
**\**Blake3.NET-master\src\Blake3" --auto-increment "" --build-metadata "" --default-pre-release-phase "" --minimum-major-minor "" --tag-prefix "" --verbosity "" --version-override """ exited with code -532462766.****

**Comment by xoofx** [comment]
> what this error mean ??

Difficult to say, but it is coming from the `MinVer` package and it could be that the path you are using is not working with it, so I would suggest to checkout your code on a simpler path like `E:\code`

**Comment by xoofx** [comment]
You can also [disable MinVer](https://github.com/adamralph/minver#can-i-disable-minver) locally if you don't want to checkout to a different folder. It is just that the version that will be pulled into the library will be wrong, but if it is to test things locally, that should still work. By adding this to `Blake3.csproj`:

```
<PropertyGroup>
  <MinVerSkip>true</MinVerSkip>
</PropertyGroup>
```
