### ISSUE TITLE
Error - Unable to load DLL 'blake3_dotnet' in .NET Framework 4.8

### ISSUE THREAD

**Issue by alexmurari** [xoofx/Blake3.NET#15]
Hi! 

First, thanks for the blake3 implementation for .NET.

I've setup a .netstandard 2.0 lib that uses Blake3 and published it in my private package feed.

But when I try to use that lib in my ASP.NET MVC 4,8 Web App, I got the following error:` "Unable to load DLL 'blake3_dotnet': The specified module could not be found."`

The dependency goes like these MyAspNet48WebApp -> MyNetStandard20Lib -> Blake3.Net.

The `blake3.dll` file is copied to the bin folder correctly, but what intrigues me is that the error message says that it's looking for a "blake3_dotnet" dll.

Do you have any thoughts here? 

Thanks!

**Comment by alexmurari** [comment]
I've created a empty .NET Framework 4.8 Console App and installed Blake3.NET package and it gave me the same error...

[ConsoleApp4.zip](https://github.com/xoofx/Blake3.NET/files/8592778/ConsoleApp4.zip)

Maybe it's related to the target frameworks settings in the artifacts publishing...

**Comment by xoofx** [comment]
It's because .NET FWK 4.8 doesn't copy the native DLLs that are in the NuGet package. You will have to copy them manually or you can do that via msbuild by adding a `GeneratePathProperty="true"` to the PackageReference, and then bring the native dll in your project. Something like that:

```xml
<ItemGroup>
    <PackageReference Include="Blake3.NET" Version="0.5.1" GeneratePathProperty="true"/>
    <Content Condition="Exists('$(PkgBlake3_NET)\runtimes\win-x64\native\blake3_dotnet.dll')" Include="$(PkgBlake3_NET)\runtimes\win-x64\native\blake3_dotnet.dll"  CopyToOutputDirectory="PreserveNewest"/>
</ItemGroup>
```

Not sure why you are using .NET 4.8 while for developing a MVC Web App, while there are newer framework in .NET 6.0.

**Comment by alexmurari** [comment]
Thanks, @xoofx! Will try that! I will let you know the result here...

The .NET 4.8 web app is from the company that I work for... the burden of legacy apps, you know...

**Comment by alexmurari** [comment]
@xoofx It does work in my test console app, but unfortunately it won't work in the web app because it doesn't support the `PackageReference` style (it uses `package.config` and it's not eligible to conversion), and i'm not in the mood to write some crazy msbuild directives to copy native dlls.

Closing this issue, since it's a .NET Framework/MsBuild limitation.

Thanks!
