### ISSUE TITLE
[Question] What is the purpose of the methods 'HashResult.CopyFromBytes(Span<byte>)' and 'Blake3Hasher.ComputerHash(Span<byte>)'?

### ISSUE THREAD

**Issue by jeffward01** [xoofx/Blake3.NET#16]
Hello!

First of all, amazing library! Thank you so much for this, this is the best Blake3 library in the C# world, and its very nice to be able to use the benefits of Blake3.

I have some questions about the API, I reviewed the [Rust API](https://docs.rs/blake3/0.3.7/blake3/#functions), and could not find a solution.

## What is the 'use-case' / reason why someone would use these methods? What do these methods do?

1.) [CopyFromBytes](https://github.com/xoofx/Blake3.NET/blob/master/src/Blake3/Hash.cs#:~:text=public%20void%20CopyFromBytes(ReadOnlySpan%3Cbyte%3E%20data))
````csharp
    public string ComputeHash(Span<byte> buffer)
    {
        // I compute a hash from bytes that I have gathered from other methods using .Write()....
        var hashResult = this._blake3Hasher.ComputeHash();
        
        // What is the purpose of this method? What would it 'do'?
        hashResult.CopyFromBytes(buffer);
        // ^^^^

        return hashResult.ToString();
    }
````

2.) [ComputeHash(Bytes)](https://github.com/xoofx/Blake3.NET/blob/master/src/Blake3/Blake3Stream.cs#:~:text=public%20void%20ComputeHash(Span%3Cbyte%3E%20hash))

````csharp

       //   I have gather some bytes to hash...
        this._blake3Hasher.Write(buffer);

        // Why would someone want to pass in 'bytes' to the compute hash?
        // They have already gatehred bytes from the .Write() method. What is the purpose 
        // of passing in the Span<byte> to ComputeHash(Span<byte>)?
        this._blake3Hasher.ComputeHash(buffer);

````

If anyone can point me to some more learning materials that would be great. the API on the readme is great, but it does not cover all of the methods of the library. 

Thanks all

**Comment by xoofx** [comment]
Documentation of `CopyFromBytes`is:

```c#
/// Copies bytes to this hash. The input data must be 32 bytes.
```

So it is just copying the span to the hash. The hash is a struct with 32 bytes. It doesn't compute a hash. It is a utility method when you have to copy some hash around through spans.
