### ISSUE TITLE
Not able to hash files

### ISSUE THREAD

**Issue by iheartcsharp** [xoofx/Blake3.NET#17]
I'm using the code below. No matter which file name I pass, it keeps returning the same hash = `af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262`. I used the MemoryStream example from the main GitHub page for this project. Why is this not working? I know the file exists, so not an issue with that.

My project type is a .NET Core 6.0 Console App in Visual Studio 2022.

    public static string Blake3(string filename)
    {
        using var blake3Stream = new Blake3Stream(File.OpenRead(filename));

        var hash = blake3Stream.ComputeHash();

        return hash.ToString();
    }

**Comment by xoofx** [comment]
You don't read anything from the stream, so the hash is a "null" hash. The stream is here to compute hash on the fly while reading (or writing). Either read the file in a `byte[]` directly and compute the hash from there or use a small buffer with the stream to read chunks into and then compute the hash when you are done.

**Comment by samuel-lucas6** [comment]
I think the `MemoryStream` README example should be changed to avoid confusion with files. I've just realised it was the cause of a a 'Stream too long' `IOException` for my program when hashing large files. I assumed it was an upstream issue based on comments like [this](https://github.com/samuel-lucas6/Milva/issues/1#issuecomment-811061696) and [this](https://github.com/BLAKE3-team/BLAKE3/issues/78#issuecomment-801425510).

Perhaps an example using `Hasher.New()` and `UpdateWithJoin()` inside a while loop reading a `FileStream`?

**Comment by manuc66** [comment]
This could be a way to hash a file:
```csharp
    public Hash HashFile(string path, int bufferSize = 4096 * 32)
    {
        using Hasher hasher = Hasher.New();
        using FileStream fs = File.OpenRead(path);
        ArrayPool<byte> sharedArrayPool = ArrayPool<byte>.Shared;
        byte[] buffer = sharedArrayPool.Rent(bufferSize);
        Array.Fill<byte>(buffer, 0);
        try
        {
            for (int read; (read = fs.Read(buffer, 0, buffer.Length)) != 0;)
            {
                hasher.Update(buffer.AsSpan(start: 0, read));
            }

            return hasher.Finalize();
        }
        finally
        {
            sharedArrayPool.Return(buffer);
        }
    }
```
