### ISSUE TITLE
Support output size 512 bit?

### ISSUE THREAD

**Issue by KevinBui1111** [xoofx/Blake3.NET#18]
Does this library support to generate hash BLAKE3 with 512 bit size, other any other size differ from 256 bit?

**Comment by xoofx** [comment]
Dunno, but I don't think Blake3 supports other than 256-bit (from their own readme). That's maybe more a question to post directly on [Blake](https://github.com/BLAKE3-team/BLAKE3)

**Comment by samuel-lucas6** [comment]
The default output size is 256 bits, but you can generate larger outputs as BLAKE3 is an XOF. This library supports using it as an XOF by passing a buffer larger than 256 bits to `Finalize()`, as shown [here](https://github.com/xoofx/Blake3.NET/blob/master/src/Blake3/Hasher.cs#LL232C28-L232C28).

**Comment by xoofx** [comment]
Oh, right, thanks, indeed, in that case you can use this method for example:

https://github.com/xoofx/Blake3.NET/blob/62d43ac0017ea48108d642969e368296eb9481f5/src/Blake3/Hasher.cs#L74-L96
