### ISSUE TITLE
Please update the native version of BLAKE3

### ISSUE THREAD

**Issue by samuel-lucas6** [xoofx/Blake3.NET#20]
[v1.2.0](https://github.com/BLAKE3-team/BLAKE3/releases/tag/1.2.0) was released in 2021, and [v1.4.1](https://github.com/BLAKE3-team/BLAKE3/releases/tag/1.4.1) seems to bring performance improvements.

I'm using this package in code for my master's dissertation that involves benchmarking, so I would be extremely grateful for this update.

**Comment by xoofx** [comment]
Should be fixed by [0.6.0](https://github.com/xoofx/Blake3.NET/releases/tag/0.6.0)

**Comment by samuel-lucas6** [comment]
Many thanks!
