### ISSUE TITLE
Support v1.0.0 of the native lib

### ISSUE THREAD

**Issue by silkfire** [xoofx/Blake3.NET#5]
Version 1.0.0 of the Rust implementation was released two months ago and it'd be nice if Blake3.NET also supported the latest version.

https://github.com/BLAKE3-team/BLAKE3/releases

**Comment by xoofx** [comment]
Yep, PR welcome

**Comment by samuel-lucas6** [comment]
[v1.1.0](https://github.com/BLAKE3-team/BLAKE3/releases/tag/1.1.0) has now been released. I would do a PR if I used Rust.

**Comment by xoofx** [comment]
Fixed in upcoming 0.4.0+

**Comment by samuel-lucas6** [comment]
I hate to be this guy, but [v1.2.0](https://github.com/BLAKE3-team/BLAKE3/releases/tag/1.2.0) has just been released with a security fix.

**Comment by silkfire** [comment]
Would it be possible to set up an automatic pipeline that emits a new version when there's a new release of the native library?
