### ISSUE TITLE
Q: Use with (binary) File (Stream)

### ISSUE THREAD

**Issue by rfrfrf** [xoofx/Blake3.NET#9]
Why are
`hash1Str`
and
`hash2Str`
**not** equal?

```
   class Program {
      static void Main(string[] args) {
         string hash1Str;
         using (BinaryReader reader = new BinaryReader(File.Open(args[0], FileMode.Open))) {
            using (var blake3Stream = new Blake3Stream(reader.BaseStream)) {
               blake3Stream.Seek(0, SeekOrigin.Begin);
               blake3Stream.ResetHash();
               Hash hash = blake3Stream.ComputeHash();
               hash1Str = hash.ToString();
            }
         }

         byte[] b = File.ReadAllBytes(args[0]);
         string hash2Str = Hasher.Hash(b).ToString();

         if (hash1Str != hash2Str) {
            Console.WriteLine("WHY?");
         }
      }
   }
```

It seems that the original blake3 exe (Windows) produces the `hash2Str`.

How can I use a stream to get the same result as  `hash2Str`?

**Comment by xoofx** [comment]
But in your example, hash1Str doesn't hash anything. You don't read from the input stream so Blake3Stream is not used at all (The seek is a nop). The Blake3Stream should be used as a pass through. You read from the Blake3Stream (or you write), it reads its content from its base stream (or write), but then it accumulates the hash for the data, until you emit a blake3Stream.ComputeHash();

See this [example in the tests](https://github.com/xoofx/Blake3.NET/blob/aa6d4e4f8f61ce0ed5f12227e728a4545fc58f1b/src/Blake3.Tests/Blake3StreamTests.cs#L12-L22).

**Comment by rfrfrf** [comment]
OMG! Thank you for your quick reply! 👍
